---
- name: install dependencies
  apt:
    name: "{{ keepalived_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - configuration
    - keepalived
    - keepalived-install
    - keepalived-install-dependencies

- name: install additional
  apt:
    name: "{{ keepalived_install }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - configuration
    - keepalived
    - keepalived-install
    - keepalived-install-additional

- name: create (checkout) directory
  file:
    path: "{{ keepalived_checkout_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - configuration
    - keepalived
    - keepalived-checkout
    - keepalived-checkout-directory

- name: checkout repository
  git:
    repo: https://github.com/acassen/keepalived.git
    dest: "{{ keepalived_checkout_path }}"
    version: "{{ keepalived_version }}"
    force: true
  register: _git_checkout
  tags:
    - configuration
    - keepalived
    - keepalived-checkout
    - keepalived-checkout-repository

- name: regenerate the build files
  shell: >
    aclocal && autoheader && automake --add-missing && autoreconf
  args:
    chdir: "{{ keepalived_checkout_path }}"
  when:
    - _git_checkout is changed
    - keepalived_version is version_compare('v1.2.24', '>=')
  tags:
    - configuration
    - keepalived
    - keepalived-build
    - keepalived-build-regenerate-build-files

- name: build
  shell: >
    ./configure {{ keepalived_configure_options | join(' ') }} && make -j{{ ansible_processor_cores + 1 }}
  args:
    chdir: "{{ keepalived_checkout_path }}"
  when: _git_checkout is changed
  tags:
    - configuration
    - keepalived
    - keepalived-build
    - keepalived-build-configure-make

- name: remove (distro version)
  apt:
    name: keepalived
    state: absent
    purge: true
  tags:
    - configuration
    - keepalived
    - keepalived-remove
    - keepalived-remove-distro

- name: install
  shell: >
    make install
  args:
    chdir: "{{ keepalived_checkout_path }}"
  when: _git_checkout is changed
  notify: reload keepalived
  tags:
    - configuration
    - keepalived
    - keepalived-install

- name: cleanup build
  shell: >
    git reset --hard && git clean -d -x -f
  args:
    chdir: "{{ keepalived_checkout_path }}"
  when: _git_checkout is changed
  tags:
    - configuration
    - keepalived
    - keepalived-cleanup
    - keepalived-cleanup-build

- name: stat directories
  stat:
    path: "{{ item }}/"
  register: _stat_directories
  with_items:
    - "{{ keepalived_configuration_file | dirname }}"
  tags:
    - configuration
    - keepalived
    - keepalived-configure-directories
    - keepalived-configure-directories-stat

- name: create directories
  file:
    path: "{{ item.item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items: "{{ _stat_directories.results }}"
  when: not item.stat.exists
  tags:
    - configuration
    - keepalived
    - keepalived-configure-directories
    - keepalived-configure-directories-create

- import_tasks: service-upstart.yml
  when: ansible_service_mgr != 'systemd'
  tags:
    - configuration
    - keepalived
    - keepalived-service
    - keepalived-service-upstart

- import_tasks: service-systemd.yml
  when: ansible_service_mgr == 'systemd'
  tags:
    - configuration
    - keepalived
    - keepalived-service
    - keepalived-service-systemd
