# tasks file for keepalived
---
- name: allow binding non-local IP
  sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: "{{ keepalived_ip_nonlocal_bind }}"
    reload: true
    state: present
  when: keepalived_ip_nonlocal_bind
  tags:
    - configuration
    - keepalived
    - keepalived-ip-nonlocal-bind

- name: add script user
  user:
    name: keepalived_script
    comment: 'keepalived script'
    home: /nonexistent
    shell: /bin/false
    system: yes
  when: keepalived_create_keepalived_script_user
  tags:
    - configuration
    - keepalived
    - keepalived-script
    - keepalived-script-user

- name: install from package manager
  include: install-package.yml
  when: keepalived_use_distro

- name: install from source
  include: install-source.yml
  when: not keepalived_use_distro

- name: update configuration file
  template:
    src: "{{ keepalived_configuration_file.lstrip('/') }}.j2"
    dest: "{{ keepalived_configuration_file }}"
    owner: root
    group: root
    mode: 0640
  notify: reload keepalived
  tags:
    - configuration
    - keepalived
    - keepalived-configuration

- name: copy script files
  copy:
    src: "{{ item.value.src }}"
    dest: "{{ item.value.dest }}"
    owner: "{{ item.value.owner | default('root') }}"
    group: "{{ item.value.group | default('root') }}"
    mode: "{{ item.value.mode | default('0750') }}"
  with_dict: "{{ keepalived_vrrp_script_map }}"
  notify: reload keepalived
  tags:
    - configuration
    - keepalived
    - keepalived-scripts

- name: start and enable service
  service:
    name: keepalived
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
  tags:
    - configuration
    - keepalived
    - keepalived-start-enable-service
